<a href="https://colab.research.google.com/github/alfie1104/pytorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- A torch.Tensor is a mlti-dimensional matrix containing elements of a single data type.
- Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
- default data type of float32.
- More suitable for deep learning than a numpy array.

In [1]:
import torch
import numpy as np

# LISTS

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.29799636, 0.7769348 , 0.81556117, 0.76126518],
       [0.22063605, 0.55587098, 0.01302949, 0.53370762],
       [0.90691041, 0.22424487, 0.63133414, 0.00793112]])

In [7]:
np1.dtype

dtype('float64')

# TENSORS

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2980, 0.7769, 0.8156, 0.7613],
        [0.2206, 0.5559, 0.0130, 0.5337],
        [0.9069, 0.2242, 0.6313, 0.0079]], dtype=torch.float64)