<a href="https://colab.research.google.com/github/alfie1104/deeplearning-with-pytorch/blob/main/4_tensor_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TENSOR MATH OPERATIONS
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and Longhand
- Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [14]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b) # 마지막에 _를 붙이면 reassign이 됨

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([ 6,  8, 10, 12])